# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Publish

on:
  push:
    branches:
      - 'master'
      - 'dev'
    tags-ignore:
      - '**' # We don't want this to run on tags pushes

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'zulu'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build and obfuscate jars
      run: ./gradlew wasmJsBrowserDistribution

    - uses: actions/upload-artifact@v4
      with:
        name: compose-files
        path: composeApp/build/dist/wasmJs/productionExecutable/

    - name: Publish docker image
      run: ./gradlew publishImage
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKERNAME }} # token name
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERSECRET }} # token secret (password)
